version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
    groups:
      avalonia-dependencies:
        patterns:
          - "Avalonia*"
      microsoft-dependencies:
        patterns:
          - "Microsoft*"
